ChatAction.Event(
    action_message=None,
    original_update=UpdateChannelParticipant(
        channel_id=2146384930,
        date=datetime.datetime(2024, 3, 18, 9, 56, 41, tzinfo=datetime.timezone.utc),
        actor_id=749179973,
        user_id=749179973,
        qts=0,
        via_chatlist=False,
        prev_participant=None,
        new_participant=ChannelParticipant(
            user_id=749179973,
            date=datetime.datetime(
                2024, 3, 18, 9, 56, 41, tzinfo=datetime.timezone.utc
            ),
        ),
        invite=ChatInviteExported(
            link="https://t.me/+U_DLllQ2...",
            admin_id=5006572203,
            date=datetime.datetime(
                2024, 3, 13, 18, 27, 15, tzinfo=datetime.timezone.utc
            ),
            revoked=False,
            permanent=True,
            request_needed=False,
            start_date=None,
            expire_date=None,
            usage_limit=None,
            usage=None,
            requested=None,
            title=None,
        ),
    ),
    new_pin=False,
    new_photo=False,
    photo=None,
    user_added=True,
    user_joined=False,
    user_left=False,
    user_kicked=False,
    unpin=True,
    created=False,
    new_title=None,
    new_score=None,
)
